export default function Policy() {
    
    return(
    <div className="flex flex-col p-5 md:p-20 bg-neutral-800 min-h-screen space-y-4 text-white"  >
        <h1 className="bold weight-400 text-2xl">Terms of service and privacy policy </h1>
        <p>These terms and conditions apply to all of Img-gen's sites, apps, and online or offline properties.</p>
        <p>By using Img-gen, you agree that you will only upload photos of yourself that you own the rights to. You may not upload photos of other people or photos that you do not have the rights to. You may not upload nude or pornographic photos. Img-gen is not responsible for any negative consequences that may result from the use of its service.</p>
        <p>To protect your privacy and security, all photos uploaded to Img-gen are permanently deleted within 24 hours after generation. The AI model trained on your photos is also permanently deleted after 24 hours. Rendered AI avatars are available for 30 days after generation.</p>
        <p>Img-gen is a registered trademark and is subject to copyright worldwide.</p>
        <p>Img-gen accepts no liability or responsibility for any reliance upon the information contained on its sites or properties.</p>
        <p>To the fullest extent permitted by applicable law, you agree that Img-gen will not be liable for any damages, including but not limited to, loss of profits, goodwill, use, data, or other intangible losses arising out of or in connection with (a) Img-gen or this agreement or the inability to use Img-gen, (b) statements or conduct of or transactions with any member or third party on Img-gen, (c) your use of Img-gen or attendance at Img-gen events, (d) participation in or exclusion from Img-gen groups or events, or (e) any other matter relating to Img-gen. Img-gen's liability to you or any third parties in any circumstance is limited to the greater of $10 or the amount of fees paid to us in the 12 months prior to the action that may give rise to liability.</p>
        <p>We make every effort to provide accurate information. However, materials contained on Img-gen's websites, apps, and properties are subject to change at any time. We give no assurance or warranty that information on this site is current and take no responsibility for matters arising from changed circumstances or other information or material which may affect the accuracy or currency of information on this site.</p>
        <p>Copyright in Img-gen's websites, apps, and properties is owned by Img-gen unless otherwise stated.</p>
        <p>Our platform serves as a conduit for the content provided by visitors and third parties. As such, we do not assume editorial responsibility for this content any more than a public library would. The opinions, advice, statements, services, offers, and other information or content made available by members, visitors, and third parties are the sole responsibility of their respective authors. We do not endorse this material in any way and expressly disclaim any liability associated with it.</p>
        <p>Any reference to products, services, hypertext links, or other information by trade name, trademark, supplier, or otherwise does not imply our endorsement, sponsorship, or recommendation. Such links are provided for convenience only, much like an index in a public library.</p>
        <p>The information on Img-gen's websites, apps, and other properties may contain technical inaccuracies or typographical errors. This information may change without notice.</p>
        <p>By using our website, you agree to maintain the confidentiality of all security features relating to your access, including login by email links and access arrangements. Img-gen is not liable for any unauthorized breach or disclosure of security features.</p>
        <p>If you use data from our APIs or site, you agree to link back to our site on the page or app screen where you use the data.</p>
        <p>We may use your user data on any of our websites and apps, including marketing pages, to show current user activity.</p>
        <p>By providing feedback, such as identifying errors or problems in our operations and services, you acknowledge and agree that all feedback will be the sole and exclusive property of Img-gen. You hereby assign to Img-gen and agree to assign to Img-gen all of your right and interest in and to all feedback, including all intellectual property rights therein.</p>
        <p>You agree to indemnify Img-gen, its employees, and agents for any loss or liability arising from any unlawful, unauthorized, or improper access or use of the Website or any breach of these terms by you or your employees, contractors, or representatives.</p>
        <p>Img-gen cannot guarantee constant availability of website access and accepts no liability for downtime or access failure due to circumstances beyond our reasonable control, including any failure by ISPs or system providers.</p>
        <p>The Site may contain links to other sites on the internet (“Linked Sites”). Img-gen is not responsible for the accuracy, legality, decency of material, or copyright compliance of any Linked Site or services or information provided via any Linked Site.</p>
        <p>While we take steps to protect your information, we cannot guarantee the security of any data transmission over the Internet. Any information you transmit to us is done so at your own risk.</p>
        <p>These terms and conditions are governed by the laws of Singapore, regardless of where Img-gen operates or you use Img-gen from.</p>
        <p>We reserve the right to permanently ban any user from our websites for behavior that goes against our guidelines. Our sole judgement will determine whether a violation of guidelines has occurred and we will not offer appeals or refunds in such cases.</p>
        <p>For EU customers, immediate access to Img-gen services is provided upon purchase and the 14-day withdrawal period is waived.</p>
        <p>Using Img-gen means agreeing not to promote any website, application, app, software, product, business, or individual by posting links or messages to direct users to them on any Img-gen site or app. If this agreement is violated, Img-gen may terminate the account and keep the membership fee as a fine.</p>
        <p>If a user's payment method is declined, Img-gen may attempt to process the transaction again under the same conditions within a few days of the first attempt. If the payment method is approved, the user will receive an email confirming the successful completion of the transaction.</p>
        <p>The information posted on our websites and apps should not be considered legal, financial, or other advice and is not intended to replace consultation with a qualified professional or specific written confirmation from Img-gen. We do not provide answers to specific legal or financial questions.</p>
        <p>Img-gen's websites, apps, and other properties are provided on an "as is," "as available" basis without warranties of any kind, express or implied, including but not limited to those of title, merchantability, fitness for a particular purpose, or non-infringement, or any warranty arising from a course of dealing, usage, or trade practice. No advice or written information provided shall create a warranty. Members or visitors to the site should not rely on any such information or advice. This publication is not intended to be a contract, explicit or implied, and Img-gen reserves the right to make changes to the information contained.</p>
        <p>The user assumes all responsibility and risk for using Img-gen's websites, apps, and properties and the internet generally. We accept no liability or responsibility to any person or organization as a consequence of reliance on the information contained on this site. Under no circumstances, including negligence, shall anyone involved in creating or maintaining Img-gen's websites, apps, and properties be liable for any direct, indirect, incidental, special, or consequential damages or loss of profits resulting from the use or inability to use the website and/or any other websites linked to this site. Nor shall they be liable for any such damages resulting from mistakes, omissions, interruptions, deletion of files, viruses, errors, defects, or failure of performance, communications failure, theft, destruction or unauthorized access. In states or countries that do not allow some or all of the above limitations of liability, liability shall be limited to the greatest extent allowed by law.</p>
        <p>Visitors are prohibited from posting on the website any unlawful, harmful, threatening, abusive, harassing, defamatory, or obscene material of any kind, including material that encourages conduct that would constitute a criminal offense, give rise to civil liability, or violate any applicable local, state, national or international law. All postings in any forum area will list the author's name and institution - no anonymous postings will be permitted.</p>
        <p>We may modify these terms from time to time. When we do, we will provide notice to you by publishing the most current version and revising the date at the top of this page. If we make any material changes to these terms, we will provide additional notice to you, such as by sending you an email or displaying a prominent notice on our platform. By continuing to use the platform after any changes come into effect, you agree to the revised terms. If you do not wish to accept the revised terms, you can close your account.</p>

 </div>
    )
}